security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        begoof_db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        begoof_secured_area:
            provider: begoof_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: default
            remember_me:
                secret: "%secret%"
                lifetime: "%remember_me_lifetime%"

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
