# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # services
    app.service.user:
        class: AppBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@service_container", "@app.service.token"]

    app.service.token:
        class: AppBundle\Service\TokenService
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]

    app.service.mailer:
        class: AppBundle\Service\MailerService
        arguments: ["@mailer", "@templating"]

    # forms
    app.form.restore:
        class: AppBundle\Form\RestoreForm
        arguments: ["@doctrine.orm.entity_manager", "@app.service.user"]
        tags:
          - { name: form.type }