default:
    path: /
    defaults: { _controller: AppBundle:Default:index }

login:
    path: /login
    defaults: { _controller: AppBundle:Auth:login }

register:
    path: /register
    defaults: { _controller: AppBundle:Auth:register }

restore:
    path: /restore
    defaults: { _controller: AppBundle:Auth:restore }

logout:
    path: /logout