# Default Controller #

default:
    path: /
    defaults: { _controller: AppBundle:Default:index }

# Auth Controller #

login:
    path: /login
    defaults: { _controller: AppBundle:Auth:login }

register:
    path: /register
    defaults: { _controller: AppBundle:Auth:register }

restore:
    path: /restore
    defaults: { _controller: AppBundle:Auth:restore }

logout:
    path: /logout

# Verify Controller #

verify_register:
    path: /verify/register
    defaults: { _controller: AppBundle:Verify:register }

verify_restore:
    path: /verify/restore
    defaults: { _controller: AppBundle:Verify:restore }